packages:
  - "01_node_daemon"
  - "02_net_http_udp"
  - "03_pnpm_workspaces_demo1"
  - "04_pnpm_workspaces_demo2"
  - "monorepo_submodule"
  - "05_process"
  - "06_eventemitter_and_stream"
  - "07_node_jwt"
  - "08_react-ssr"
  - "09_other_module"
  - "10_web_stream"
  - "11_pi_calculation"
  - "12_URL"
  - "13_decorator"
# install common dependencies: `pnpm add xxx -w` -w equal --workspace-root
# install dependencies for specifics packages: `pnpm add xxx 03_pnpm_workspaces_demo1`
